//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_02.Models
{
    using PP_02.Utils;
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class ServicePhoto
    {
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Service Service { get; set; }

        public String GetPathPhoto
        {
            get
            {
                String filePath = $"{Constants.ServiceAdditiveImgFolder}\\{this.PhotoPath}";
                if (File.Exists(filePath))
                {
                    return filePath;
                }
                return $"{Constants.ServiceImgFolder}{Constants.Service404Img}";
            }
        }
    }
}
